name: CI
on: [push]
jobs:
  Build3.8:
    runs-on: python:3.8
    steps:
      - run: echo "Build tap on python 3.8"
      - run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - run: poetry build
